# Generated by Django 3.2.20 on 2023-07-06 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_catagory_duration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Duration',
            new_name='Catagory',
        ),
    ]
